### ISSUE TITLE
Optional constexpr support

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [CPPAlliance/json#104]
Just an idea, I don't think it is necessary at the moment.

**Comment by vinniefalco** [comment]
But constexpr how? constexpr parsing? What?

**Comment by WPMGPRoSToTeMa** [comment]
> constexpr parsing?

Yes.

> Note this library requires only C++11, which does not have robust support for constexpr in the first place.

I mean constexpr can be enabled only for C++14 (or 17/20 if something is not available) and higher.

**Comment by vinniefalco** [comment]
I don't see much utility in constexpr parsing. It would basically have to be a completely separate implementation. And then how could it allocate the necessary memory? The `memory_resource` interface uses virtual functions.

**Comment by vinniefalco** [comment]
Please descrinbe the use-case(s) for `constexpr` JSON parsing?

**Comment by WPMGPRoSToTeMa** [comment]
> And then how could it allocate the necessary memory?

C++20 allows memory allocation inside constexpr functions, however allocated memory cannot escape a constexpr context.

> The `memory_resource` interface uses virtual functions.

C++20 allows constexpr virtual functions.

> Please describe the use-case(s) for `constexpr` JSON parsing?

No idea :smiley:, but I can imagine the following:
1. Embed content of json data file in source code.
2. Then parse it at compile-time.
3. Then convert it to a specific type.
4. Finally store the result of (3) in read-only memory of application and use it at run-time.

**Comment by vinniefalco** [comment]
That doesn't sound very compelling, considering the enormous amount of work needed. The purpose of this library is to parse JSON at run-time and produce a DOM.
