### ISSUE TITLE
Optional `char8_t` support

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [CPPAlliance/json#105]
Just an idea, I don't think it is necessary at the moment. Probably can perform better because of different aliasing rules. The problem can be that all the parsing things typically work only with `char`.

**Comment by vinniefalco** [comment]
This is a C++11 library. And I don't see how `char8_t` can possibly improve performance. Perhaps you can show me on godbolt.org?

**Comment by Eelis** [comment]
https://godbolt.org/z/1bqzbY is an example of how `char8_t` can improve performance (notice how `slow` does more memory accesses than `fast`, because unlike `fast`, `slow` can't be sure that `*p = '3';` doesn't modify `i`).

**Comment by vinniefalco** [comment]
This might be good for serialization, but when parsing we use `char const*` not `char*`. And we don't write to the input.

**Comment by Eelis** [comment]
Writing to the input is not essential; here's a modified example where the input is not written to, but `char8_t` still gives an advantage: https://godbolt.org/z/njKj3s

**Comment by vinniefalco** [comment]
so what we can do is make a private alias in `basic_parser`:
```
#ifdef __cpp_has_char8
using char_type = char8_t;
#else
using char_type = char;
#endif
```

And then change `char const*` to `char_type const*` internally, doing a big `reinterpret_cast` on entry, and get all these benefits?

**Comment by Eelis** [comment]
I don't know, I haven't used `char8_t` for real yet, only played with it in godbolt snippets. :)

**Comment by vinniefalco** [comment]
can't hurt to try

**Comment by sdkrystian** [comment]
By doing a reinterpret_cast we alias the input as `char8_t`... and end up with UB

**Comment by vinniefalco** [comment]
Is it really UB though? Or is it only UB in papers that float through WG21? Can you show UB for this using an existing compiler?

**Comment by vinniefalco** [comment]
Yes it is technically UB, so we can't embrace this just yet. I'd like to see what the performance is like after refactoring to use a nested `char_type` set to `char8_t`. Then we can revisit the topic. After 1.75 release though.

**Comment by vinniefalco** [comment]
I don't see this as practical
