### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by smalls12** [CPPAlliance/json#106]
Hello,

Trying to compile BeastLounge and buildling this library as it is a dependency.

Getting the following error:
```
CMake Error at CMakeLists.txt:114 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "boost_json".
```

I'm guessing this might be a specific issue for my system

Ubuntu 18.04
gcc 7.5.0
cmake 3.10.2

**Comment by qis** [comment]
@smalls12 Hello. Would you be so kind and test if #107 resolves your problem?

**Comment by smalls12** [comment]
Yup fixed.
Thanks :)
