### ISSUE TITLE
Documentation/code clash on value::value(kind)

### ISSUE THREAD

**Issue by AeroStun** [CPPAlliance/json#110]
On `devel` (`ef48831` at the time of writing)

Docs say
```cpp
// json/doc/qbk/02_1_values.qbk:50
value jv( kind::object );
```
and
```cpp
// json/doc/qbk/02_1_values.qbk:64
jv = value( kind::array )
```
however the code does not allow for these statements, as no ctor for `value` takes a `kind`
Instead the code supports the values `object_kind` and `array_kind` (which are validated by tests)

Same applies to `kind::string` and `string_kind`

Ran into that issue while converting an exitsting codebase from rapidjson to Boost.JSON

**Comment by vinniefalco** [comment]
Thanks for pointing this out! I should note that Boost.JSON, is not officially part of Boost yet, it is awaiting a review manager and then a review. And it is still beta software. That said, it has extensive tests and coverage, and the API is mostly stable. We plan on supporting optional comments and optional utf-8 validation of input. The documentation still needs some refinement. However the library should work well for you and it has been extensively optimized. Don't hesitate to ask further questions or raise new issues, it will help us polish this thing!

**Comment by vinniefalco** [comment]
Code snippets in the docs are compiled, `value( kind::array )` should not compile I wonder what is going on...

**Comment by vinniefalco** [comment]
Ah, I see. The code in 02_1_values.qbk needs to be turned into snippets which are compiled. Then, this kind of mistake will be detected.
