### ISSUE TITLE
valid json reported as invalid

### ISSUE THREAD

**Issue by bhendrickson** [CPPAlliance/json#113]
The file below contains a valid json string. However, the boost json example program `validate` reports it is invalid, and the example program `pretty` reports `caught exception: extra data`. 

[valid_json_boost_json_issue.txt](https://github.com/CPPAlliance/json/files/4803279/valid_json_boost_json_issue.txt)

Many small changes to the string makes it parse correctly, such as deleting an innocuous looking character from the string.

I've reproduced this on the tip of master (f47fbeb1a54b832221a35c17912febb7a2c3a317) with both clang and gcc.

Please let me know any additional information I can provide that would be helpful.

**Comment by sdkrystian** [comment]
@bhendrickson It seems like we were forgetting to flush the buffer after parsing escape sequences, causing the parse to be incomplete.
