### ISSUE TITLE
Docs for tuple-like interface

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#120]
`get` will be missing some javadocs when the PR is merged. It should probably be done like this:
```
#ifdef BOOST_JSON_DOCS

/** Tuple-like interface
*/
template< std::size_t I, class T >
__see_below__
get( T&& );

#else

// actual defintions

#endif
```

**Comment by sdkrystian** [comment]
Exposition could use some work:

> As with `std::pair`, `key_value_pair` implements the required specializations of `std::tuple_element`, `std::tuple_size`, and get to function as a tuple-like type. This means that it can be used as the initializer in a structured binding declaration: [snippet]
