### ISSUE TITLE
(Question) boost::json::string as key of associative array?

### ISSUE THREAD

**Issue by tomasgareau** [CPPAlliance/json#133]
Trying to use boost::json::string as a key in (e.g.,) an unordered map

```
#include "boost/json/string.hpp"

#include <unordered_map>

int main(int argc, char** argv) {
  std::unordered_map<boost::json::string, int> map;
  boost::json::string s = "test";
  map.insert(s, 10);
}
```

fails to compile, giving:

```
 error: static_assert failed
      due to requirement '__check_hash_requirements<string, hash<string> >::value' "the specified hash
      does not meet the Hash requirements"
```

This is easy enough to work around by converting to e.g., std::string but is a bit awkward. I'm fairly new to some of the rationale & concepts behind boost::json::string as [described in the docs](http://vinniefalco.github.io/doc/json/json/usage/strings.html) and so was wondering: is there is a reason behind this/a different intended way to use strings as keys/some other explanation?

**Comment by vinniefalco** [comment]
The library needs to provide a specialization of `std::hash` for `json::string`. It will be done, thanks!

**Comment by tomasgareau** [comment]
There's a turnaround to write home about :) Thanks!

**Comment by vinniefalco** [comment]
Sorry it took so long, we ran into a bug in libstdc 4.8 :)
