### ISSUE TITLE
Benchmark stability

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#152]
The current method we use for benchmarking isn't entirely stable with large numbers of trials. File data could be flushed from the cache using `_mm_clflush` in between runs, and there might be a way to flush the instructions cache too.

**Comment by vinniefalco** [comment]
Define "stable." When I have 10 trials, most of them have exactly the same throughput. The benchmark program discards the outliers (top and bottom 2 or so). If you are getting different results, I would suspect your hardware is the culprit.

**Comment by sdkrystian** [comment]
If you run a benchmark 20 times on a file (once for develop and once for your branch) the benchmark that runs second will have a significant advantage because it's likely that the file is entirely within the cache (and at a lower level),

**Comment by vinniefalco** [comment]
I don't see why. If Trials==20, then the file will be cached on the first trial of the first benchmark. Why would the file only become cached on all the trials of the second branch?

**Comment by sdkrystian** [comment]
The more a resource is used, the lower it gets in the cache hierarchy.

**Comment by vinniefalco** [comment]
I don't think this matters
