### ISSUE TITLE
Is basic_parser::max_depth() == 32 the right default:

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#163]
This affects the `parse` free functions, since users cannot control the parser it uses

**Comment by sdkrystian** [comment]
How was the number chosen in the first place?

**Comment by vinniefalco** [comment]
16 seemed too small and 64 seemed too large :) but seriously...I"m not sure, maybe it came from the spec as a suggestion.

**Comment by vinniefalco** [comment]
Check this out:
https://softwareengineering.stackexchange.com/questions/279207/how-deeply-can-a-json-object-be-nested

**Comment by sdkrystian** [comment]
I feel that we can go deeper still; our parse functions don't use all that much stack space (or we might be worse than nlohmann as we use SSE2)

**Comment by vinniefalco** [comment]
The purpose of having a small default depth is to be "secure by default." The number 32 isn't set in stone though, we can consult with Bishop Fox to see if this number should be changed.

**Comment by vinniefalco** [comment]
I think 32 is gud. If users complain we can change it later.
