### ISSUE TITLE
Store depth_ as max_depth_ - [actual depth]

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#164]
Using this method max depth is exceeded when `parse_array` or `parse_object` is called and `depth_ == 0`. After this check, we can safely decrement `depth_` without overflow. 

This eliminates a read from memory as we need not compare with `max_depth_`. We should probably specify what happens when depth is changed and the parser is suspended.

**Comment by vinniefalco** [comment]
calling `write_some` after changing the max depth is undefined. You have to call `reset` first.

**Comment by sdkrystian** [comment]
Ah, we should document this then
