### ISSUE TITLE
key_value_pair missing swap

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#179]
Missing `swap` member and free function. I am struggling to see the use-case, this issue is here just so we don't forget.

**Comment by sdkrystian** [comment]
Not sure if it's "missing" anything. Sure `std::pair` has `swap`, but that's more general purpose than `key_value_pair`

**Comment by vinniefalco** [comment]
we have it for all the other container types. not trying to argue for it, just pointing out facts.

**Comment by vinniefalco** [comment]
If a user complains, we can revisit.
