### ISSUE TITLE
Homogeneous value_builder stack

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#189]
We already track these in `basic_parser`, so there's no point in having people track this themselves

**Comment by vinniefalco** [comment]
`value_builder` still has to track it, since it can be used without the parser.

**Comment by sdkrystian** [comment]
Preliminary research: ~7% increase on `citm_catalog`, `canada` and `twitter`, but a ~7% drop on `random` and `small`.

**Comment by vinniefalco** [comment]
The research is a dead-end, because we can't use two allocations in `value_builder`.

**Comment by sdkrystian** [comment]
Again, this doesn't require multiple allocations.

**Comment by sdkrystian** [comment]
We already track the size in `basic_parser`, so this eliminates a bunch of reads and writes from memory within `value_builder`

**Comment by sdkrystian** [comment]
Storing keys as values on the stack will save memory -- to do so we need to add a "key kind" and store it as a `string`.

**Comment by vinniefalco** [comment]
This is done
