### ISSUE TITLE
Clarifying Dox for Monotonic Resources

### ISSUE THREAD

**Issue by JonKalb** [CPPAlliance/json#191]
On this page: http://vinniefalco.github.io/doc/json/json/usage/allocators.html
The first paragraph under Monotonic Resources contains a sentence that begins _This implementation allocates large blocks of memory and then allocates within these blocks to satisfy allocation requests…_. This sentence uses the word _allocates_ twice, but the two uses refer to different actions which could confuse some users.

Suggesting: _This implementation **acquires** large blocks of memory and then allocates from **within** these blocks to satisfy allocation requests…_

**Comment by vinniefalco** [comment]
ooh nice wording

**Comment by sdkrystian** [comment]
Closed by 5dc6125352be1e03c157e868a2d5a7f3363dd6da
