### ISSUE TITLE
Useful resources

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#2]
http://seriot.ch/parsing_json.php
https://github.com/nst/JSONTestSuite
https://github.com/cyb70289/utf8/
https://github.com/lemire/fastvalidate-utf-8

**Comment by podsvirov** [comment]
@vinniefalco  you saw the [json](https://github.com/nlohmann/json) for `C++`  implementatied by @nlohmann?

**Comment by vinniefalco** [comment]
> @vinniefalco you saw the json for C++ implementated by @nlohmann?

Yes, of course!
