### ISSUE TITLE
Add parse_options to `parse` free functions

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#206]
As the last paramete, defaulted to `{}`

**Comment by sdkrystian** [comment]
Do we want a default parameter or seperate overloads? Default parameter means that we require a `storage_ptr` to be passed if the user wants to specify parse options

**Comment by vinniefalco** [comment]
Peter says default parameter. Otherwise, this is ambiguous:
```
parse( s, ec, {} );
```

**Comment by sdkrystian** [comment]
Ah, ok
