### ISSUE TITLE
testNumberRoundTrips has disabled code

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#214]
`testNumberRoundTrips` in serializer.cpp has tests which are commented out

**Comment by sdkrystian** [comment]
This is already done in `parser.cpp`

**Comment by vinniefalco** [comment]
If the commented out tests are redundant we should remove them. But how can that be, if one is in the serializer and the other is in the parser? What happens when we uncomment?

**Comment by sdkrystian** [comment]
Round trip implies that when we parse then serialize, we get the same thing. `parser.cpp` does just that :)

**Comment by vinniefalco** [comment]
Look more closely at the tests:
```
        //BOOST_TEST(parse("-0.0").as_double() == -0);
        //BOOST_TEST(parse("-0").as_int64() == 0);
        //BOOST_TEST(to_string(parse("0.0")) == "0");
        //BOOST_TEST(to_string(parse("-0.0")) == "-0.0");

        // VFALCO Peter is unsure what this should do
        //BOOST_TEST(to_string(parse("-0")) == "-0");
```

So you're saying parser.cpp checks `parse("-0.0").as_double() == -0` ?
And it checks `to_string(parse("0.0")) == "0"` ?
