### ISSUE TITLE
Handler not invoked correctly in multi-byte UTF8 sequences, part 2

### ISSUE THREAD

**Issue by rtobar** [CPPAlliance/json#240]
This was fixed for writes of size 1 in #162, but apparently not for the general case, see https://github.com/rtobar/json/commit/6d766ef6643429296e6368513849ff1f49384c4f for a test reproducing further errors plus a new example string that breaks.

**Comment by sdkrystian** [comment]
*sigh* I forgot to flush characters preceding UTF-8 byte sequences. My bad.

**Comment by rtobar** [comment]
Looks good, thanks!
