### ISSUE TITLE
use std::align, boost::align

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#245]
We should use `std::align` or `boost::align` as needed, since those are portable.

**Comment by sdkrystian** [comment]
Is there any reason to even use `boost::align`? `std::align` is available in C++11

**Comment by vinniefalco** [comment]
> std::align is available in C++11

That is true, but older clang and gcc stdlibs don't have it. Just take my code from here:
https://github.com/CPPAlliance/json/blob/57d7eb8e7f4845f6d36a8693b5809d92cffbf843/include/boost/json/impl/static_resource.ipp#L26

And put it in `<boost/detail/align.hpp>, include it from both places, and use it.

**Comment by sdkrystian** [comment]
@vinniefalco Should I get rid of `detail::align_up` too?
