### ISSUE TITLE
Optional bench and build time cloning of nlohmann and rapidjson

### ISSUE THREAD

**Issue by ayounes-synaptics** [CPPAlliance/json#26]
Hello,
Thanks for this library, I find it very interesting, especially for deeply embedded platform (without OS).
I feel that having nlohmann and rapidjson imposed as git submodule just for the purpose of benchmarking is too much. Full cloning of nlohmann in particular is quite big...
What about moving that to build time retrieving thanks to cmake ExternalProject_Add?

include(ExternalProject)
ExternalProject_Add(bench/lib/nlohmann
  GIT_REPOSITORY    https://github.com/nlohmann/json.git
  GIT_TAG           99d7518d21cbbfe91d341a5431438bf7559c6974
)

Also compilation of bench should be optional.

Thanks!

**Comment by vinniefalco** [comment]
I will look into it but remember that this is going to be proposed for Boost, and you will get the library through Boost, not through git. In that configuration there will be no submodule or benchmark program.

**Comment by ayounes-synaptics** [comment]
Thanks.
As a side note, just for information, I think a lot of people like the fact that this library can be used in standalone, independently from boost. Also Modularized boost is actually using git submodule and I guess it will use this git?

**Comment by vinniefalco** [comment]
> Modularized boost is actually using git submodule and I guess it will use this git?

Ah, so some other project is doing a deep fetch of the submodules in my json lib?

**Comment by ayounes-synaptics** [comment]
> > Modularized boost is actually using git submodule and I guess it will use this git?
> 
> Ah, so some other project is doing a deep fetch of the submodules in my json lib?

Exactly yes.

**Comment by vinniefalco** [comment]
Maybe I can just put a bash script there instead which clones the necessary repositories and specific commit ids, and remove the submodules.

**Comment by ayounes-synaptics** [comment]
> Maybe I can just put a bash script there instead which clones the necessary repositories and specific commit ids, and remove the submodules.

That would also work indeed. But ExternalProject_Add() will do that for you and even call cmake automatically at build time on the child project (if using cmake).

**Comment by vinniefalco** [comment]
Oh... :) That looks very nice, I will try that.

**Comment by vinniefalco** [comment]
We went the bash script route, which places less burden on the CML file.
