### ISSUE TITLE
prime table operation is not 32-bit safe

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#270]
This line causes a warning:
https://github.com/CPPAlliance/json/blob/adacd6670cd92ef5b8e2890550a7a6171e86d854/include/boost/json/impl/object.ipp#L512

The way it is written, it looks like we can get a `*prime` that exceeds the max unsigned 32-bit integer. Then the assignment will underflow.

**Comment by sdkrystian** [comment]
I'll write the table so that the maximum value is `4294967295` on 32 bit
