### ISSUE TITLE
serialize array, object, string, underlying types

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#275]
See if the `serializer` can be refactored to support serializing the container types and possibly the underlying types (like `double`). Provide overloads of `to_string` and `operator<<` for these types.

**Comment by pdimov** [comment]
Doesn't this work automatically due to these types being convertible to `json::value`?

**Comment by vinniefalco** [comment]
No, because the serializer stores a pointer to the value being serialized:
https://github.com/CPPAlliance/json/blob/adacd6670cd92ef5b8e2890550a7a6171e86d854/include/boost/json/serializer.hpp#L66

To make this work, serializer needs to type-erase the top-level thing being serialized, probably by changing `jv_` to be `void*`, and storing a pointer to an overloaded member function. The existing write_* members should probably take a const ref to the thing they are serializing, to avoid depending on `jv_` being a `value const*`.

**Comment by pdimov** [comment]
I was talking about `to_string` and `operator<<`.

**Comment by vinniefalco** [comment]
> I was talking about to_string and operator<<.

Yikes... yes. Those will make a copy :(
