### ISSUE TITLE
Document BOOST_NO_EXCEPTIONS

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#285]
The overview should explain the use of this macro for Boost and for standalone

**Comment by pdimov** [comment]
There's no "use" of this macro under the Boost configuration - it's automatically set by Boost.Config and automatically respected by boost::throw_exception.

On standalone, the standard feature macro is `__cpp_exceptions`, I'm not sure how reliable it is. There are compiler-specific macros (from memory, `__EXCEPTIONS` on GCC, `_CPPUNWIND` on MSVC.)
