### ISSUE TITLE
Default resource performance could be improved

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#294]
This is probably because we use a singleton.

**Comment by vinniefalco** [comment]
No it is because calls to the system `allocate` and `deallocate` are expensive

**Comment by sdkrystian** [comment]
That's irrelevant, RapidJSON outperforms us anyways and they use `malloc` (which has identical performance)

**Comment by sdkrystian** [comment]
Addressed by da65b25f4df7d3e090e4a700cdf14df026062c3c
