### ISSUE TITLE
Hash function needs a salt

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#3]
This needs a good hash function for strings, and we should probably guard against algorithmic complexity attacks by allowing for a salt.

**Comment by Knackie** [comment]
i can help u :)

**Comment by vinniefalco** [comment]
Okay, well... don't keep me in suspense! What did you have in mind?

**Comment by Knackie** [comment]
probably use std::hash
Or bash command

**Comment by vinniefalco** [comment]
`std::hash` doesn't have a salt

**Comment by Knackie** [comment]
or with hashlib, if  you define a string as salt

![image](https://user-images.githubusercontent.com/43431712/66476586-4bd8bc80-ea96-11e9-99db-02e51a92c523.png)

**Comment by vinniefalco** [comment]
Is that C++? SHA256 looks a bit too strong for a hash function used to drive an unordered map...

**Comment by Knackie** [comment]
u can use different SHA like SHA1

Le mer. 9 oct. 2019 à 13:26, Vinnie Falco <notifications@github.com> a
écrit :

**Comment by 0xdead4ead** [comment]
How about looking an easy implementation PBKDF2?

**Comment by vinniefalco** [comment]
> PBKDF2

We don't need cryptographic strength here

**Comment by vinniefalco** [comment]
We can use the address of the implementation as the salt, since that doesn't change until a rehash.
