### ISSUE TITLE
value_stack performance improvements

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#316]
There is still quite a bit of performance we can squeeze out of `value_stack`, at the same time reducing binary size. For example, allocations and copying should be done within the `value_stack` `push_object/array/key/string` functions. If the allocation throws, then `~value_stack` will clean up for us, so stack unwinding segments don't need to be generated.

Example implementation here: https://github.com/sdkrystian/json/tree/stack-rework-1

**Comment by vinniefalco** [comment]
This is no good at all, it breaks encapsulation so we will not be doing it.
