### ISSUE TITLE
Size of string for 32bit builds

### ISSUE THREAD

**Issue by maximilianriemensberger** [CPPAlliance/json#335]
If I'm not mistaken the string type in this library has 12 bytes in size for 32bit builds due to the key_string union member, see  https://github.com/CPPAlliance/json/blob/fc7b1c6fd229e884df09fd45c64c6102d2aa129b/include/boost/json/detail/string_impl.hpp#L80

Considering that there are careful checks for the sbo and pointer member that they are exactly 8 byte sized, this feels rather odd. Also for 64 bit builds, all three are 16 bytes.

Was that intended?  An if so, why waste those 4 chars in the sbo version?

**Comment by vinniefalco** [comment]
This looks like a regression:
```
boost.json.zsizes
sizeof(alignof)
  object        == 12 (4)
    value_type  == 32 (8)
  array         == 12 (4)
  string        == 16 (4)
  value         == 16 (8)
  serializer    == 72
  parser        == 120
```

**Comment by vinniefalco** [comment]
Yes it looks like we are missing out on 4 characters worth of small buffer for the 32-bit builds!!!
