### ISSUE TITLE
value_to behavior for reference types

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#363]
Right now we error if `T` is a reference type

**Comment by sdkrystian** [comment]
@vinniefalco Is this actionable?

**Comment by vinniefalco** [comment]
I think we are supposed to error, we should just make sure that the constraints and/or static assertions are the way that we want them. I think this is more about double checking the SFINAE expressions to make sure they are right.

**Comment by sdkrystian** [comment]
We already do error

**Comment by vinniefalco** [comment]
Nothing actionable then.
