### ISSUE TITLE
Array push_back

### ISSUE THREAD

**Issue by djarek** [CPPAlliance/json#364]
Currently, calling `json_array.push_back(json_array.back())` results in undefined behavior if `push_back` causes a reallocation. This is different behavior than exhibited by `std::vector`, for which self-referential `push_back` is valid. Either the documentation should contain an explicit warning about this difference, or the implementation should be amended to follow `std::vector`'s practice.

Additionally, the documentation for `push_back` claims the Strong Exception guarantee, however, the implementation invalidates references if constructing the array element throws.

Note that both issues apply to `emplace_back` as well.

**Comment by vinniefalco** [comment]
Should work now thanks
