### ISSUE TITLE
CMAKE_CXX_STANDARD in cmake/toolchains/common.cmake is ignored

### ISSUE THREAD

**Issue by mloskot** [CPPAlliance/json#69]
```
cmake -B _build.gcc -DBOOST_JSON_STANDALONE=ON -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/gcc.cmake
cmake -B _build.gcc -DCMAKE_CXX_STANDARD=14 -DBOOST_JSON_STANDALONE=ON -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/gcc.cmake
```

Something seems fishy in how  `set(CMAKE_CXX_STANDARD 11 CACHE STRING "")` is handled, the `src/src.cpp` is compiled with `-std=c++17` but the `test/limits.cpp` with `-std=c++11` or with `-std=c++14`  (the second command).

The fish has been fished:

https://github.com/CPPAlliance/json/blob/d92902c7cf259f4103a0b798050f50ae5b8aa289/CMakeLists.txt#L63

Then, the `common.cmake` needs something like this perhaps

```
if(BOOST_JSON_STANDALONE)
    set(CMAKE_CXX_STANDARD 17 CACHE STRING "")
else()
    set(CMAKE_CXX_STANDARD 11 CACHE STRING "")
endif()
```

**Comment by qis** [comment]
Yes, this is quite unexpected…

https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards

Here it clearly states that `target_compile_features(mylib PUBLIC cxx_std_11)` "[…] applies to sources within `mylib` as well as any dependents (that may include headers from `mylib`)."

Could it be a CMake version and/or policy issue? Setting `CMAKE_CXX_STANDARD` in directory scope for a build that includes tests/examples might be a good idea.

**Comment by mloskot** [comment]
> Could it be a CMake version and/or policy issue?

No idea. I'm using CMake 3.17.0

**Comment by Mike-Devel** [comment]
Are you guys aware that there are two test binaries generated? One with all the test source files and linked against `boost_json`, the other uses on limits.cpp and main.cpp and does not link against `boost_json`. So it isn't a wonder that cxx_std_17 doesn't get propagated in the second case.

**Comment by qis** [comment]
@Mike-Devel I was not aware of that. Thank you!

**Comment by mloskot** [comment]
@Mike-Devel Me neither and I only looked into the `common.cmake`. That `cxx_std_17` was pointed out by @vinniefalco

**Comment by vinniefalco** [comment]
Yep sorry about that. The "limits" test compiles limits.cpp, is something I added to CMakeLists.txt that was already built in the Jamfile. This test changes configuration macros which affect the compiled library, thus limits is compiled in the "header-only" configuration:
https://github.com/CPPAlliance/json/blob/7784fdd45bbc2abab4e179b0ac70c675ace5a582/test/CMakeLists.txt#L24

**Comment by vinniefalco** [comment]
I have refactored the CML with Peter's help. We've added an item to the Travis matrix for standalone building with cmake, to ensure things stay working. Please try the new branch and let me know if it works for you.

**Comment by mloskot** [comment]
Yes, it works. The `FATAL_ERROR` works too. Thanks!

**Comment by mloskot** [comment]
@vinniefalco 
> We've added an item to the Travis matrix for standalone building with cmake, to ensure things stay working.

The removed GitHub Actions covered several more of the supported modes that this. May be worth to port.

**Comment by vinniefalco** [comment]
> The removed GitHub Actions covered several more of the supported modes that this. May be worth to port.

Yep, as soon as someone holds my hand I'll crank out the other configurations.
