### ISSUE TITLE
Dynamic cast causes code to fail to compile with -fno-rtti on gcc

### ISSUE THREAD

**Issue by edtanous** [CPPAlliance/json#75]
https://github.com/CPPAlliance/json/blob/ad1a3378b6caac61da44bec403336a02d3fd381f/include/boost/json/detail/default_resource.hpp#L47

The above line prevents compilation if -fno-rtti is enabled in gcc (version 9, but I suspect that doesn't matter)

In member function ‘virtual bool boost::json::detail::default_resource::do_is_equal(const boost::container::pmr::memory_resource&) const’:
...boost/json/detail/default_resource.hpp:48:41: error: ‘dynamic_cast’ not permitted with ‘-fno-rtti’

This appears to be a regression on this commit:
https://github.com/CPPAlliance/json/commit/a47b0f3fc16980afa644f6f3c0d62aa11e687e4c

Backing up to one commit previous allows the same code to build and link just fine.

**Comment by vinniefalco** [comment]
Yeah I always forget about `-fno-rtti`. How do you suggest to fix it?

**Comment by edtanous** [comment]
I don't understand enough about what that code is doing to render an opinion for how to fix it.  I'll try to dig deeper in the next day or two to be able to speak intelligently about it and put up a PR.

I was hoping it was something easy :)

**Comment by vinniefalco** [comment]
>I don't understand enough about what that code is doing to render an opinion for how to fix it.

Well, I think we need to do two things:

1. Determine if RTTI is turned off (some kind of ifdef or compiler setting), and
2. Decide how we want the function to behave with RTTI off. For example we could always return `false`.

**Comment by vinniefalco** [comment]
Can we simply just always return `false` here?

**Comment by edtanous** [comment]
Pulled it down.  Issue solved.  Thanks for the quick turnaround and the great work on this library.  It really does seem to solve some problems.
