### ISSUE TITLE
Generic conversion from map to object

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#88]
`to_value` could use an internal overload that converts a map-like object (key/value pairs) to a `json::object`.

**Comment by madmongo1** [comment]
There are a few separate concerns here IMHO:

1. represent an object as JSON (without necessarily _converting_ it)
2. parse an object from JSON representation (without necessarily going through a value object)
3. actual conversion to/from json

**Comment by vinniefalco** [comment]
"object" here refers specifically to `json::object` while "map" refers specifically to any _ForwardRange_ whose value type is convertible to `json::key_value_pair`.

**Comment by sdkrystian** [comment]
Added in #103
